# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/demo_zc706/demo_zc706.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo_zc706 || ORIG_REF_NAME==demo_zc706} -quiet] -quiet

# IP: bd/demo_zc706/ip/demo_zc706_processing_system7_0_0/demo_zc706_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo_zc706_processing_system7_0_0 || ORIG_REF_NAME==demo_zc706_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/lgonzales/Documents/Vivado/code/demo_zc706/demo_zc706.gen/sources_1/bd/demo_zc706/ip/demo_zc706_processing_system7_0_0/demo_zc706_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==demo_zc706_processing_system7_0_0 || ORIG_REF_NAME==demo_zc706_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lgonzales/Documents/Vivado/code/demo_zc706/demo_zc706.gen/sources_1/bd/demo_zc706/demo_zc706_ooc.xdc
